id: D8AD334A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T11:05:41+00:00'
last_modified: '2022-05-30T07:49:32.195710+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '4071':
      image_group_id: I1PD95942
      title: ཚད་མ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1198
      order: 97
      base_file: 4071.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
