id: P2713E9A3
initial_creation_type: ocr
source_metadata:
  volumes:
    1268d2bc65f74f53a76465857fef2114:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
